django_cases/myproject/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^showproject/', include('showproject.urls',namespace='showproject')),
] + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

django_cases/showproject/urls.py
from django.conf.urls import url,include

from . import views
urlpatterns = [

    url(r'^index/', views.index),
    url(r'^provice/', views.provice, name='provice'),
    url(r'^city/', views.city, name='city'),
    url(r'^hello/', views.city, name='hello'),
]

django_cases/showproject/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.conf.urls import url,include
from django.contrib import admin
from django.db import models
from django.conf import settings
from django.conf.urls.static import static
from django.db import models
# Create your models here.
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^showproject/', include('showproject.urls', namespace='showproject')),
]+ static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

class Tag(models.Model):
    name = models.CharField(max_length=30, verbose_name='标签名称')

    class Meta:
        verbose_name = '标签'
        verbose_name_plural = verbose_name
        ordering = ['id']

    def __unicode__(self):
        return self.name

django_cases/showproject/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render
from django.http import HttpResponse
import json
from models import *

# Create your views here.
def index(request):
    return render(request, 'index.html')
def provice(request):
    return render(request, 'provice.html')

def city(request):
    myjson = {
        'type': 'column',
        'colorByPoint': 'true',
        'data': [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4],
        'showInLegend': 'false'
    }
    data = json.dumps(myjson)
    return render(request, 'city.html', locals())

def hello(request):
    myjson = {
        'type': 'column',
        'colorByPoint': 'true',
        'data': [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4],
        'showInLegend': 'false'
    }
    data = json.dumps(myjson)
    return render(request, 'hello.html', locals())

django_cases/showproject/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>welcome</title>
</head>
<body>
    <h1>Welcome to Django</h1>
</body>
</html>

django_cases/templates/city.html
{% extends 'layout.html' %}
{% load staticfiles %}

{% block content %}

    <script src="{% static 'hchart/highcharts.js' %}"></script>
	<script src="{% static 'hchart/modules/exporting.js' %}"></script>
    <div id="container"></div>



	<script>
	$(function () {
	    var  val= [{{ data | safe }}]
    var chart = Highcharts.chart('container', {
        title: {
            text: '图表变换'
        },
        subtitle: {
            text: '普通的'
        },
        xAxis: {
            categories: ['一月', '二月', '三月', '四月', '五月', '六月', '七月', '八月', '九月', '十月', '十一月', '十二月']
        },
        series:val
    });



});
</script>


{% endblock %}


{% block js %}

   <script>
      $(function () {
          $('#city').addClass('active')
          $('#aa').accordion('select','区域管理');
      })

   </script>

{% endblock %}

django_cases/templates/hello.html
{% extends 'layout.html' %}
{% load staticfiles %}

{% block content %}

    <script src="{% static 'hchart/highcharts.js' %}"></script>
	<script src="{% static 'hchart/modules/exporting.js' %}"></script>
    <div id="container"></div>



	<script>
	$(function () {
	    var  val= [{{ data | safe }}]
    var chart = Highcharts.chart('container', {
        title: {
            text: '图表变换'
        },
        subtitle: {
            text: '普通的'
        },
        xAxis: {
            categories: ['一月', '二月', '三月', '四月', '五月', '六月', '七月', '八月', '九月', '十月', '十一月', '十二月']
        },
        series:val
    });



});
</script>


{% endblock %}


{% block js %}

   <script>
      $(function () {
          $('#city').addClass('active')
          $('#aa').accordion('select','区域管理');
      })

   </script>

{% endblock %}

django_cases/templates/index.html
{% extends 'layout.html' %}

{% block content %}
  <h1 align="center">welcome</h1>
{% endblock %}


{% block js %}

   <script>
      $(function () {
          $('#provice').remove('active')
      })

   </script>

{% endblock %}

django_cases/templates/layout.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<title>Complex Layout - jQuery EasyUI Demo</title>
	<link rel="stylesheet" type="text/css" href="{% static 'ui/themes/default/easyui.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'ui/themes/icon.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'ui/demo/demo.css' %}">
	<script type="text/javascript" src="{% static 'ui/jquery.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'ui/jquery.easyui.min.js' %}"></script>
	<style>
	.jd-menu{
	   display:block;
	   padding: 8px;
	   border-bottom:1px solid #ddd ;
	}
	.active{
	   background:#3b5998;
	   color:white;
	}
	</style>
</head>
<body class="easyui-layout">


		<div data-options="region:'north'" style="height:50px"></div>
		<div data-options="region:'south',split:true" style="height:50px;"></div>

		<div data-options="region:'west',split:true" title="菜单" style="width:100px;">
			<div id ="aa" class="easyui-accordion" data-options="fit:true,border:false">
				<div title="区域管理"  style="padding:10px;">
					<a id='provice' class='jd-menu' href="{% url 'showproject:provice' %}" >省</a>
                    <a id ='city' class='jd-menu' href="{% url 'showproject:city' %}">市</a>
                    <a id ='hello' class="jd-menu" href="{% url 'showproject:hello' %}">县</a>
				</div>
				<div title="用户管理" data-options="selected:true" style="padding:10px;">
					content2
				</div>
				<div title="商户管理" style="padding:10px">
					content3
				</div>
			</div>
		</div>
		<div data-options="region:'center',title:'主页',iconCls:'icon-ok'">
		      {% block content %}{% endblock %}
		</div>
      {% block js %}
      {% endblock %}

</body>
</html>

django_cases/templates/provice.html
{% extends 'layout.html' %}
{% load staticfiles %}

{% block content %}

	<script src="{% static 'hchart/highcharts.js' %}"></script>
	<script src="{% static 'hchart/modules/exporting.js' %}"></script>

<div id="container" style="min-width:400px;height:400px"></div>

	<script>
	$(function () {
    $('#container').highcharts({
        chart: {
            type: 'line'
        },
        title: {
            text: '月平均气温'
        },
        subtitle: {
            text: '数据来源: WorldClimate.com'
        },
        xAxis: {
            categories: ['一月', '二月', '三月', '四月', '五月', '六月', '七月', '八月', '九月', '十月', '十一月', '十二月']
        },
        yAxis: {
            title: {
                text: '气温 (°C)'
            }
        },
        plotOptions: {
            line: {
                dataLabels: {
                    enabled: true          // 开启数据标签
                },
                enableMouseTracking: false // 关闭鼠标跟踪，对应的提示框、点击事件会失效
            }
        },
        series: [{
            name: '东京',
            data: [7.0, 6.9, 9.5, 14.5, 18.4, 21.5, 25.2, 26.5, 23.3, 18.3, 13.9, 9.6]
        }, {
            name: '伦敦',
            data: [3.9, 4.2, 5.7, 8.5, 11.9, 15.2, 17.0, 16.6, 14.2, 10.3, 6.6, 4.8]
        }]
    });
});
</script>



{% endblock %}


{% block js %}

   <script>
      $(function () {
          $('#provice').addClass('active')
          $('#aa').accordion('select','区域管理');
      })

   </script>

{% endblock %}

django_cases/templates/test.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
        "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <title>Title</title>
</head>
<body>

</body>
</html>